name: nexrad_level_ii
description: "A package for reading and parsing NEXRAD Level II data files."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.3.4
dependencies:
  archive: 3.5.1
  test: 1.25.4
