name: Dart

on:
  push:
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
      - name: Install Dart
        uses: dart-lang/setup-dart@v1.6.4
      - name: Install Dart dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze --fatal-infos
      - name: Run tests
        run: dart test --coverage="coverage"
      - name: Install coverage tools
        run: dart pub global activate coverage
      - name: format coverage
        run: $HOME/.pub-cache/bin/format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib
      - uses: codecov/codecov-action@v4.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: USA-RedDragon/dart-nexrad-level-ii
          files: coverage.lcov
