name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
      - name: Install Dart
        uses: dart-lang/setup-dart@v1.6.4
      - name: Install Dart dependencies
        run: dart pub get
