name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
    environment: pub.dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
      - name: Install Dart
        uses: dart-lang/setup-dart@v1.6.4
      - name: Install Dart dependencies
        run: dart pub get
      - name: Replace pubspec version with tag version
        run: |
          export GIT_TAG_SEMVER="${GITHUB_REF_NAME##v}"
          echo "Setting version to $GIT_TAG_SEMVER"
          yq ".version = strenv(GIT_TAG_SEMVER)" -i pubspec.yaml
          git tag -d ${GITHUB_REF_NAME}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Release $GIT_TAG_SEMVER" pubspec.yaml
          git tag ${GITHUB_REF_NAME} -m "${GITHUB_REF_NAME}"
          git push -f origin ${GITHUB_REF_NAME}
      - name: Publish
        run: dart pub publish --dry-run
      - name: Generate CHANGELOG.md
        run: |
          exit 1
